const SET_TODO = "SET_TODO";
const EDIT_TODO = "EDIT_TODO";
const ADD_TODO = "ADD_TODO";
const START_EDIT_TODO = "START_EDIT_TODO";
const END_EDIT_TODO = "END_EDIT_TODO";
const DELETE_TODO = "DELETE_TODO";

export {
  SET_TODO,
  EDIT_TODO,
  ADD_TODO,
  START_EDIT_TODO,
  END_EDIT_TODO,
  DELETE_TODO,
};
